name: Update Portainer Container

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send POST request to Portainer webhook
        run: |
          # Replace the URL with your Portainer webhook URL
          PORTAINER_WEBHOOK_URL="https://162.19.224.10:9443/api/webhooks/161bc599-bc3d-49c2-b06f-5e108f9fab9a"
    
          # Send the POST request to trigger the update (with insecure option)
          curl -k -X POST -d '{}' "$PORTAINER_WEBHOOK_URL"
